/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kopr.GUI;

import DatabaseConnector.Mysql;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import com.mysql.cj.conf.BooleanPropertyDefinition;
import java.awt.Color;
import java.util.Date;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import kopr.defaultAccess.Auth;
import kopr.manager.KopRManager;
import kopr.systemCompatibility.GetRequirementS;
import oshi.SystemInfo;
import oshi.hardware.ComputerSystem;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.software.os.OperatingSystem;

/**
 *
 * @author Mobius
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    boolean theAuthenticationMod = false;
    
    Auth auth = new Auth("karyawan_auth");
    
    public Login() {
        initComponents();
        
    }
    
    public int mikuTalk(int mikuWannaSays) {
        switch (mikuWannaSays) {
            case 0 -> {
                mikuSays.setText("log o in to");
                mikuSays2.setText("");
                mikuSays3.setText("");
                mikuSays.setForeground(Color.BLACK);
                return mikuWannaSays + 1;
            }
            case 5 -> {
                mikuSays3.setText("jika anda");
                mikuSays2.setText("gk punya akun");
                mikuSays.setText("tekan miku");
                mikuSays.setForeground(Color.BLACK);
                mikuSays2.setForeground(Color.BLACK);
                mikuSays3.setForeground(Color.BLACK);
                return mikuWannaSays + 1;
            }
            default -> {
                if (mikuWannaSays == 10) {
                    return 0;
                }
                return mikuWannaSays + 1;
            }
        }
    }
    
    public boolean showLogin() {
        setVisible(true); // Menampilkan JFrame Login
        setLocationRelativeTo(null);

        // Menunggu sampai JFrame ditutup
        int c = 0;
        while (isVisible()) {
            try {
                //Thread.sleep(100); // Memberi jeda agar aplikasi tidak freeze
                //System.out.println("number: " + c);
                Thread.sleep(1000);
                c = mikuTalk(c);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        
        return theAuthenticationMod; // Mengembalikan hasil login
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mikuSays3 = new javax.swing.JLabel();
        mikuSays = new javax.swing.JLabel();
        mikuSays2 = new javax.swing.JLabel();
        hidenButtonForDb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(450, 300));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/20241210_193528.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        mikuSays3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mikuSays3.setForeground(new java.awt.Color(0, 204, 204));
        mikuSays3.setText("|");

        mikuSays.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mikuSays.setForeground(new java.awt.Color(0, 204, 204));
        mikuSays.setText("|");

        mikuSays2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mikuSays2.setForeground(new java.awt.Color(0, 204, 204));
        mikuSays2.setText("|");

        hidenButtonForDb.setForeground(new java.awt.Color(0, 204, 204));
        hidenButtonForDb.setText("CSDB");
        hidenButtonForDb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidenButtonForDbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mikuSays, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mikuSays3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mikuSays2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hidenButtonForDb))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mikuSays3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mikuSays2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mikuSays)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(hidenButtonForDb)
                .addContainerGap())
        );

        jButton1.setText("An!chor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });

        jLabel1.setText("User");

        jLabel2.setText("pass");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoadingLoginOrigin loadingLogin = new LoadingLoginOrigin();
        String user = txtUser.getText();
        char[] pass = txtPass.getPassword();
        String passA = new String(pass);
        boolean keyLSystem;
        
        try {
            if (auth.login(user, passA)) {
                JOptionPane.showMessageDialog(this, "Login Berhasil!");
                theAuthenticationMod = true;
                // kunci base132
                GetRequirementS ssd = new GetRequirementS();
                Date dt = new Date();
                try {
                    //loadingLogin.showFrameLoadSDA();
                    JOptionPane.showMessageDialog(null, "proses akan memakan waktu tergantung pada device anda", "Information", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("halo belum log");
                    String informationLog = "InformationApp at " + dt.toString();
                    ssd.sendEmail(informationLog, ssd.getCompatibilityApp());
                } catch (MessagingException e) {
                    JOptionPane.showMessageDialog(null, "anda tidak terhubung ke internet, klik ok untuk melanjutkan");
                }
                keyLSystem = auth.localKeyLogCFG("config/key.properties", user, passA);// harus dipindahkan ke sisi execution before app close
                System.out.println("halo sudah log");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "wrongg!!");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean oneChange;
    boolean eventMikuSet;
    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
//        try {
//            Thread.sleep(2000);
//            //if (!oneChange) {
//                mikuSays.setText("hi!");
//                //TimeUnit.SECONDS.sleep(3);
//                mikuSays.setText("Log o In to");
//                //oneChange = true;
//            } else {
//            }
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jLabel3MouseEntered
    

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
//        if (!eventMikuSet) {
//            mikuSays.setText("Log o In to");
//        }
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
//        mikuSays.setText("cepat login :(");
//        eventMikuSet = true;
        ImageIcon icon = new ImageIcon("C:\\Users\\Mobius\\Documents\\NetBeansProjects\\EsquiDaQoprasias\\src\\resource\\20241210_193517.png");
//        switch (JOptionPane.showOptionDialog(this, "apakah anda mau daftar, pastikan punya encodeNya dari manajer", "Register Miku", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icon, null, 0)) {
//            case 0:
//                
//                break;
//            case 1:
//                
//                break;
//            default:
//                System.out.println("chs: " + );
//        }
        String[] typeChoose = {"yes", "no", "encode?"};
        System.out.println("chs: " + JOptionPane.showOptionDialog(this, "apakah anda mau daftar, pastikan punya encodeNya dari manajer", "Register Miku", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, icon, typeChoose, -1));
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            java.awt.event.ActionEvent evte = null;
            jButton1ActionPerformed(evte);
        }
    }//GEN-LAST:event_formKeyPressed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPassActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:
        formKeyPressed(evt);
    }//GEN-LAST:event_txtPassKeyPressed

    private void hidenButtonForDbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidenButtonForDbMouseClicked
        // TODO add your handling code here:
        //change db
        String urlCustom = JOptionPane.showInputDialog(null, "masukkan url, ex: domainName/dbName", "custom-URL-DB", JOptionPane.WARNING_MESSAGE);
        try {
            if (!urlCustom.isEmpty()) {
                String userCustom = JOptionPane.showInputDialog(null, "userCustom DB", "custom-DB", JOptionPane.WARNING_MESSAGE);
                String passCustom = JOptionPane.showInputDialog(null, "passCustom DB", "custom-DB", JOptionPane.WARNING_MESSAGE);
                Mysql.setCustomDatabase(urlCustom, userCustom, passCustom);
                JOptionPane.showMessageDialog(null, "memulai ulang aplikasi");
                
                String java = System.getProperty("java.home") + "/bin/java";
                String classPath = System.getProperty("java.class.path");
                String className = KopRManager.class.getName();
                
                ProcessBuilder pcb = new ProcessBuilder(java, "-cp", classPath, className);
                pcb.inheritIO();
                pcb.start();
                
                this.dispose();
                System.exit(0);
            } else {
                System.out.println("cancel no argument");
            }
        } catch (Exception e) {
            System.out.println("cancel click");
        }
    }//GEN-LAST:event_hidenButtonForDbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidenButtonForDb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mikuSays;
    private javax.swing.JLabel mikuSays2;
    private javax.swing.JLabel mikuSays3;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
